id = "ziggy"
name = "Ziggy"
version = "0.0.2"
schema_version = 1
authors = ["Louis Vignoli <louis.vignoli@gmail.com>"]
description = "Ziggy and ziggy schema support for Zed"
repository = "https://github.com/lvignoli/zed-ziggy"

[grammars.ziggy]
repository = "https://github.com/kristoff-it/ziggy"
commit = "a246334e7a1d3f43f9f76a4af6c6d179d37b188f"
path = "tree-sitter-ziggy"

[grammars.ziggy_schema]
repository = "https://github.com/kristoff-it/ziggy"
commit = "a246334e7a1d3f43f9f76a4af6c6d179d37b188f"
path = "tree-sitter-ziggy-schema"

[language_servers.ziggy]
name = "Ziggy LSP"
language = "ziggy"
