name = "ziggy-schema"
grammar = "ziggy_schema"
path_suffixes = ["ziggy-schema"]
line_comments = ["// "]

brackets = [
    { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "{", end = "}", close = true, newline = true},
    { start = "[", end = "]", close = true, newline = true},
]
